name: financial-analysis
channels:
  - defaults
dependencies:
  - numpy=1.21.5
  - openpyxl=3.0.9
  - pandas=1.4.1
  - pip=21.2.4
  - python=3.10.0
  - jupyter
  - python-dateutil=2.8.2
  - scikit-learn=1.0.2
  - setuptools=58.0.4
  - statsmodels=0.13.0
  - wheel=0.37.1
  - pyyaml
